org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

mod_version=1.1.0
maven_group=net.mintymc
archives_base_name=emf_distance_cutoff

fabric_api_version=0.158.0+26.2
emf_curse_file=8309557
etf_curse_file=8266310
modmenu_version=20.0.0
